export const links = [
    {
        name:"Solutions",
        submenu:true,
        sublink:[
            {
                name:'Carriers',
                link:'/carriers'
            },
            {
                name:'Brokers',
                link:'/brokers'
            },
            {
                name:'Shippers',
                link:'/shippers'
            },
        ]
    },
    {
        name:"Recources",
        submenu:true,
        sublink:[
            {
                name:'Guide',
                link:'/guide'
            },
            {
                name:'Blogs',
                link:'/blog'
            },
            {
                name:'Videos',
                link:'https://www.youtube.com/'
            },
        ]
    },
]